class StaticPagesController < ApplicationController
  def contact
  end

  def tester
    logger.debug('++++++++++ '+ENV['SMTP_SERVER'])
    logger.debug("++++++++++ #{Figaro.env.smtp_user}")
    logger.debug("++++++++++ "+Figaro.env.smtp_port.class.to_s)
      to='ronaldf@eml.cc'
    msg = <<EOM
From: #{Figaro.env.smtp_from}
To: <#{to}>
Subject: test net/smtp

Testmessage generated by StaticPagesController Tester via net/smtp
EOM
    # Defined in application.yml
    Net::SMTP.start(
      Figaro.env.smtp_server,
      Figaro.env.smtp_port,
      'localhost', # HELO domain
      Figaro.env.smtp_user,
      Figaro.env.smtp_pass,
      :login) { |smtp| smtp.send_mail msg,Figaro.env.smtp_from,to }
    redirect_to root_path, notice: 'StaticPagesController: Test message sent.'
  end
end
